channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=pyhd3eb1b0_0
  - anyio=4.2.0=py311hca03da5_0
  - appnope=0.1.2=py311hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h80987f9_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311hca03da5_0
  - attrs=23.1.0=py311hca03da5_0
  - babel=2.11.0=py311hca03da5_0
  - backoff=2.2.1=py311hca03da5_1
  - beautifulsoup4=4.12.3=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h313beb8_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - branca=0.6.0=py311hca03da5_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py311h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.9.24=hca03da5_0
  - cairo=1.16.0=h302bd0f_5
  - cartopy=0.22.0=py311h7aedaa7_0
  - certifi=2024.8.30=py311hca03da5_0
  - cffi=1.17.1=py311h3eb5a62_0
  - cfitsio=3.470=h7f6438f_7
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py311hca03da5_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - comm=0.2.1=py311hca03da5_0
  - contextily=1.3.0=pyhd8ed1ab_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py311hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h313beb8_0
  - fiona=1.9.5=py311h7aedaa7_0
  - folium=0.14.0=py311hca03da5_0
  - fontconfig=2.14.1=h6402c1e_3
  - fonttools=4.51.0=py311h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - freexl=2.0.0=ha3de405_0
  - gdal=3.6.2=py311h950983f_5
  - geoalchemy2=0.9.2=pyhd3eb1b0_0
  - geographiclib=1.52=pyhd8ed1ab_0
  - geojson=3.1.0=pyhd8ed1ab_0
  - geopandas=0.13.2=pyhd8ed1ab_1
  - geopandas-base=0.13.2=pyha770c72_1
  - geoplot=0.5.1=pyhd8ed1ab_0
  - geopy=2.4.0=pyhd8ed1ab_0
  - geos=3.9.1=hc377ac9_1
  - geotiff=1.7.0=h41f0982_3
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.1=h80987f9_3
  - glib=2.69.1=h514c7bf_2
  - greenlet=3.0.1=py311h313beb8_0
  - hdf4=4.2.13=h5e329fb_3
  - hdf5=1.12.1=h05c076b_3
  - icu=73.1=h313beb8_0
  - idna=3.7=py311hca03da5_0
  - importlib-metadata=7.0.1=py311hca03da5_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py311hca03da5_0
  - ipykernel=6.28.0=py311hca03da5_0
  - ipython=8.27.0=py311hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.19.1=py311hca03da5_0
  - jinja2=3.1.4=py311hca03da5_0
  - joblib=1.4.2=py311hca03da5_0
  - jpeg=9e=h80987f9_3
  - json-c=0.16=h1a28f6b_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311hca03da5_0
  - jsonschema-specifications=2023.7.1=py311hca03da5_0
  - jupysql=0.10.14=pyhd8ed1ab_0
  - jupysql-plugin=0.4.5=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=py311hca03da5_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311hca03da5_0
  - jupyter_events=0.10.0=py311hca03da5_0
  - jupyter_server=2.14.1=py311hca03da5_0
  - jupyter_server_terminals=0.4.4=py311hca03da5_1
  - jupyterlab=4.0.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py311hca03da5_0
  - kealib=1.5.0=hba2eb73_1
  - kiwisolver=1.4.4=py311h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcurl=8.9.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgdal=3.6.2=h51eea9d_5
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libkml=1.3.0=hc4d7c42_7
  - libnetcdf=4.8.1=h0fce390_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libpq=12.17=h02f6b3c_0
  - libsodium=1.0.18=h1a28f6b_0
  - libspatialindex=1.9.3=hc377ac9_0
  - libspatialite=5.1.0=h3e2df84_1
  - libssh2=1.11.0=h3e2b118_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.13.1=h0b34f26_2
  - libzip=1.8.0=h62fee54_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - mapclassify=2.5.0=py311hca03da5_0
  - markupsafe=2.1.3=py311h80987f9_0
  - matplotlib=3.9.2=py311hca03da5_0
  - matplotlib-base=3.9.2=py311hecf7826_0
  - matplotlib-inline=0.1.6=py311hca03da5_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - minizip=4.0.3=ha89c15f_0
  - mistune=2.0.4=py311hca03da5_0
  - monotonic=1.5=py_0
  - nbclient=0.8.0=py311hca03da5_0
  - nbconvert=7.10.0=py311hca03da5_0
  - nbformat=5.9.2=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - networkx=3.3=py311hca03da5_0
  - notebook=7.0.4=pyhd8ed1ab_0
  - notebook-shim=0.2.3=py311hca03da5_0
  - nspr=4.35=h313beb8_0
  - nss=3.89.1=h313beb8_0
  - numexpr=2.8.7=py311h6dc990b_0
  - numpy=1.26.4=py311he598dae_0
  - numpy-base=1.26.4=py311hfbfe69c_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.0.15=h80987f9_0
  - overrides=7.4.0=py311hca03da5_0
  - packaging=24.1=py311hca03da5_0
  - pandas=2.2.2=py311h7aedaa7_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hc377ac9_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py311h80987f9_0
  - pip=24.2=py311hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=3.10.0=py311hca03da5_0
  - ploomber-core=0.2.25=pyhd8ed1ab_0
  - ploomber-extension=0.1.1=pyhd8ed1ab_0
  - poppler=22.12.0=h52f4003_3
  - poppler-data=0.4.11=hca03da5_1
  - posthog=3.6.5=pyhd8ed1ab_0
  - proj=9.3.1=h805f6d4_0
  - prometheus_client=0.14.1=py311hca03da5_0
  - prompt-toolkit=3.0.43=py311hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h80987f9_0
  - psycopg2=2.9.9=py311h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311hca03da5_1
  - pyparsing=3.1.2=py311hca03da5_0
  - pyproj=3.6.1=py311h041c639_0
  - pyshp=2.3.1=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.9=hb885b13_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-fastjsonschema=2.16.2=py311hca03da5_0
  - python-json-logger=2.0.7=py311hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py311hca03da5_0
  - pyyaml=6.0.1=py311h80987f9_0
  - pyzmq=24.0.1=py311h80987f9_0
  - qhull=2020.2=h48ca7d4_2
  - rasterio=1.3.10=py311hd30b564_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py311hca03da5_0
  - requests=2.32.3=py311hca03da5_0
  - rfc3339-validator=0.1.4=py311hca03da5_0
  - rfc3986-validator=0.1.1=py311hca03da5_0
  - rpds-py=0.10.6=py311hf0e4da2_0
  - rtree=1.0.1=py311hca03da5_0
  - scikit-learn=1.5.1=py311h7aedaa7_0
  - scipy=1.13.1=py311hac8794a_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.2=py311hca03da5_0
  - setuptools=75.1.0=py311hca03da5_0
  - shapely=2.0.5=py311h3713c0e_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py311hca03da5_0
  - snuggs=1.4.7=pyhd3eb1b0_0
  - soupsieve=2.5=py311hca03da5_0
  - sqlglot=25.10.0=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - sqlparse=0.4.4=py311hca03da5_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py311hca03da5_0
  - threadpoolctl=3.5.0=py311hb6e6a13_0
  - tiledb=2.3.3=hb4a6b97_3
  - tinycss2=1.2.1=py311hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tomli=2.0.1=py311hca03da5_0
  - tornado=6.4.1=py311h80987f9_0
  - traitlets=5.14.3=py311hca03da5_0
  - typing-extensions=4.11.0=py311hca03da5_0
  - typing_extensions=4.11.0=py311hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h80987f9_0
  - uriparser=0.9.7=h80987f9_0
  - urllib3=2.2.3=py311hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311hca03da5_1
  - websocket-client=1.8.0=py311hca03da5_0
  - wheel=0.44.0=py311hca03da5_0
  - xerces-c=3.2.4=h313beb8_1
  - xyzservices=2022.9.0=py311hca03da5_1
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.17.0=py311hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.5=hd90d995_2
  - pip:
      - geodatasets==2023.3.0
      - ipython-sql==0.5.0
      - pandas-geojson==1.2.0
      - prettytable==3.9.0
      - simplekml==1.3.6
      - sqlalchemy==2.0.23
